/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package tugas_4;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author User
 */
public class FormUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormUtama.class.getName());
    
    static int harga=30000;
    static int total;
    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        
        // Mengatur spinner agar minimum 1 dan maksimum 10
        SpinnerNumberModel model =
            new SpinnerNumberModel(1, 1, 10, 1);
        spnJumlah.setModel(model);
        
        // Mengatur formatting utk formatted field agar sesuai dengan currency indonesia
        NumberFormat formatID = NumberFormat.getNumberInstance(
            new Locale("id", "ID")
        );

        NumberFormatter formatter = new NumberFormatter(formatID);
        formatter.setAllowsInvalid(false);

        fieldUang.setFormatterFactory(
         new DefaultFormatterFactory(formatter)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTab = new javax.swing.JTabbedPane();
        tabPemesanan = new javax.swing.JPanel();
        lblJudul1 = new javax.swing.JLabel();
        tbtnMember = new javax.swing.JToggleButton();
        lblMember = new javax.swing.JLabel();
        lblNamaFilm = new javax.swing.JLabel();
        spnJumlah = new javax.swing.JSpinner();
        lblHarga = new javax.swing.JLabel();
        lblJumlahTiket = new javax.swing.JLabel();
        lblTotalHargaPesan = new javax.swing.JLabel();
        lblPemesanan = new javax.swing.JLabel();
        tabPembayaran = new javax.swing.JPanel();
        lblKembalian = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        barProgress = new javax.swing.JProgressBar();
        lblPembayaran = new javax.swing.JLabel();
        lblUang = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        lblTotalHargaBayar = new javax.swing.JLabel();
        fieldUang = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CinemaXIX");

        lblJudul1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJudul1.setText("Cinema XIX");
        lblJudul1.setMinimumSize(new java.awt.Dimension(0, 0));
        lblJudul1.setPreferredSize(new java.awt.Dimension(174, 18));

        tbtnMember.setText("Tidak aktif");
        tbtnMember.addActionListener(this::tbtnMemberActionPerformed);

        lblMember.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblMember.setText("Status member");

        lblNamaFilm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNamaFilm.setText("Film                         Jatuh Cinta Seperti di Film-Film (2023)");

        spnJumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        spnJumlah.addChangeListener(this::spnJumlahStateChanged);

        lblHarga.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHarga.setText("Harga tiket              Rp30.000");

        lblJumlahTiket.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblJumlahTiket.setText("Jumlah tiket         ");

        lblTotalHargaPesan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalHargaPesan.setText("Total harga              Rp30000");

        lblPemesanan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPemesanan.setText("Pemesanan");

        javax.swing.GroupLayout tabPemesananLayout = new javax.swing.GroupLayout(tabPemesanan);
        tabPemesanan.setLayout(tabPemesananLayout);
        tabPemesananLayout.setHorizontalGroup(
            tabPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPemesananLayout.createSequentialGroup()
                        .addComponent(lblPemesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(lblJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253))
                    .addGroup(tabPemesananLayout.createSequentialGroup()
                        .addGroup(tabPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamaFilm)
                            .addGroup(tabPemesananLayout.createSequentialGroup()
                                .addComponent(lblJumlahTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotalHargaPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabPemesananLayout.createSequentialGroup()
                                .addComponent(lblMember, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(tbtnMember, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabPemesananLayout.setVerticalGroup(
            tabPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPemesananLayout.createSequentialGroup()
                .addGroup(tabPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPemesananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabPemesananLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblPemesanan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamaFilm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahTiket)
                    .addComponent(spnJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnMember)
                    .addComponent(lblMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalHargaPesan)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelTab.addTab("Pemesanan", tabPemesanan);

        lblKembalian.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblKembalian.setText("Kembalian             ");

        lblHasil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblJudul.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblJudul.setText("Cinema XIX");
        lblJudul.setMinimumSize(new java.awt.Dimension(0, 0));
        lblJudul.setPreferredSize(new java.awt.Dimension(174, 18));

        lblPembayaran.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPembayaran.setText("Pembayaran");

        lblUang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUang.setText("Uang");

        btnBayar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBayar.setText("Bayar");
        btnBayar.setBorder(null);
        btnBayar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBayar.addActionListener(this::btnBayarActionPerformed);

        lblTotalHargaBayar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTotalHargaBayar.setText("Total harga              Rp30000");

        fieldUang.addActionListener(this::fieldUangActionPerformed);

        javax.swing.GroupLayout tabPembayaranLayout = new javax.swing.GroupLayout(tabPembayaran);
        tabPembayaran.setLayout(tabPembayaranLayout);
        tabPembayaranLayout.setHorizontalGroup(
            tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPembayaranLayout.createSequentialGroup()
                .addGroup(tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPembayaranLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabPembayaranLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabPembayaranLayout.createSequentialGroup()
                                .addComponent(lblUang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(fieldUang, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotalHargaBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPembayaran))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
            .addGroup(tabPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabPembayaranLayout.createSequentialGroup()
                        .addComponent(lblKembalian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabPembayaranLayout.createSequentialGroup()
                    .addGap(262, 262, 262)
                    .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(209, 209, 209)))
        );
        tabPembayaranLayout.setVerticalGroup(
            tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPembayaranLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabPembayaranLayout.createSequentialGroup()
                        .addComponent(lblPembayaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalHargaBayar)
                        .addGap(3, 3, 3)
                        .addGroup(tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUang)
                            .addComponent(fieldUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKembalian)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(tabPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabPembayaranLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(186, Short.MAX_VALUE)))
        );

        panelTab.addTab("Pembayaran", tabPembayaran);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        
        // Mengambil value dari fieldUang -> convert ke number kemudian ke integer
        int uang = ((Number) fieldUang.getValue()).intValue();
        // Jika harga lebih besar, tampilin uang nggak cukup
        if (uang < harga){
        lblHasil.setText("Uang kamu nggak cukup");
        return;
        }
    // Mengatur progres bar setelah pengguna klik bayar
    barProgress.setValue(0);
    // 0-100
    Timer timer = new Timer(100, null);
    
    timer.addActionListener(e -> {
        int nilai = barProgress.getValue();
        if (nilai < 100){
            barProgress.setValue(nilai + 10); // +10 setiap progress, selama belum 100
        }else{
            timer.stop();
            int kembalian = uang - total; // Mengatur kembalian
            lblHasil.setText("Rp" +kembalian); // Tampilin kembalian
        }
    });
    timer.start();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void tbtnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnMemberActionPerformed
        // TODO add your handling code here:
        if (tbtnMember.isSelected()){
            tbtnMember.setText("Aktif");
            lblHarga.setText("Harga tiket              Rp25.000");
            harga = 25000;
        }else{
            tbtnMember.setText("Tidak Aktif");
            lblHarga.setText("Harga tiket              Rp30.000");
            harga = 30000;
        }
    }//GEN-LAST:event_tbtnMemberActionPerformed

    private void spnJumlahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnJumlahStateChanged
        // TODO add your handling code here:
        int jumlah = (int) spnJumlah.getValue();
        total = jumlah * harga;
        lblTotalHargaPesan.setText("Total harga              Rp"+total);
        lblTotalHargaBayar.setText("Total harga              Rp"+total);
    }//GEN-LAST:event_spnJumlahStateChanged

    private void fieldUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barProgress;
    private javax.swing.JButton btnBayar;
    private javax.swing.JFormattedTextField fieldUang;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul1;
    private javax.swing.JLabel lblJumlahTiket;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblNamaFilm;
    private javax.swing.JLabel lblPembayaran;
    private javax.swing.JLabel lblPemesanan;
    private javax.swing.JLabel lblTotalHargaBayar;
    private javax.swing.JLabel lblTotalHargaPesan;
    private javax.swing.JLabel lblUang;
    private javax.swing.JTabbedPane panelTab;
    private javax.swing.JSpinner spnJumlah;
    private javax.swing.JPanel tabPembayaran;
    private javax.swing.JPanel tabPemesanan;
    private javax.swing.JToggleButton tbtnMember;
    // End of variables declaration//GEN-END:variables
}
